# Generated by Django 5.1.3 on 2025-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_product_image4_remove_product_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 2348012345678)', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 2348012345678)', max_length=20),
        ),
    ]
