# Generated by Django 5.1.3 on 2025-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_whatsapp_number_service_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 23480XXXXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 23480XXXXXXXX', max_length=20),
        ),
    ]
