# Generated by Django 4.2.7 on 2025-12-17 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marked_unavailable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marked_unavailable_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unavailable_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, help_text='Cloudinary video URL (30-90 seconds)'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_duration',
            field=models.IntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='marked_unavailable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='marked_unavailable_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unavailable_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.URLField(blank=True, help_text='Cloudinary video URL (30-90 seconds)'),
        ),
        migrations.AddField(
            model_name='service',
            name='video_duration',
            field=models.IntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 23480XXXXXXXX)', max_length=20),
        ),
    ]
